[config]

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -USR1 -x kitty'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.polybar]
input_path = '~/.config/matugen/templates/polybar.ini'
output_path = '~/.dotfiles/polybar/colors.ini'
post_hook = 'polybar-msg cmd restart'

[templates.dunst]
input_path = '~/.config/matugen/templates/dunstrc'
output_path = '~/.config/dunst/dunstrc'

[templates.niri]
input_path = '~/.config/matugen/templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'

[templates.eww]
input_path = '~/.config/matugen/templates/eww.scss'
output_path = '~/.config/eww/colors.scss'

[templates.greetd]
input_path = '~/.config/matugen/templates/greetd.css'
output_path = '/var/cache/matugen/greetd.css'

[templates.refind]
input_path = '~/.config/matugen/templates/refind.json'
output_path = '/var/cache/matugen/refind-colors.json'
#post_hook = '~/.dotfiles/scripts/refind-matugen.sh /var/cache/matugen/refind-colors.json'
