[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]
# `agreety` is the bundled agetty/login-lookalike. We start Hyprland with nwg-hello instead.
command = "Hyprland --config /etc/nwg-hello/hyprland.conf"
user = "greeter"
